<a href="https://colab.research.google.com/github/Bishesh-P/Next-Word-Predictor-LSTM/blob/main/Next_Word_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [89]:
data = """I love machine learning
I love deep learning
I love artificial intelligence
I like machine learning
I like deep learning
Machine learning is interesting
Machine learning is powerful
Machine learning is useful
Deep learning is powerful
Deep learning is interesting
Deep learning uses neural networks
Artificial intelligence is changing the world
Artificial intelligence is very useful
Neural networks are powerful
Neural networks can learn patterns
Neural networks are used in deep learning
Deep learning can solve complex problems
Machine learning can solve many problems
I am learning machine learning
I am learning deep learning
I am studying artificial intelligence
I am studying neural networks
The model learns from data
The model predicts the next word
The model can learn patterns
The model is trained on data
The neural network learns patterns
The neural network predicts words
Data is important for machine learning
Data is used to train the model
Training the model takes time
Training the neural network takes time
The model learns from examples
The model improves with more data
More data can improve the model
Machine learning models learn from data
Deep learning models use neural networks
Neural networks learn from examples
I want to learn machine learning
I want to learn deep learning
I want to build a neural network
I want to build a prediction model
I want to predict the next word """

In [90]:
extra_data = """Machine learning is a branch of artificial intelligence
Deep learning is a subset of machine learning
Neural networks are inspired by the human brain
A neural network has many layers
Each layer learns different features
Data scientists clean the data before training
Good data leads to a good model
Bad data leads to a bad model
The model is evaluated on test data
The model is tested on new data
Accuracy measures how well the model performs
A high accuracy means the model is good
Overfitting happens when the model memorizes the data
Underfitting happens when the model is too simple
More layers can improve the model
Regularization helps reduce overfitting
The loss function measures the error of the model
The optimizer updates the weights of the model
Gradient descent minimizes the loss function
The learning rate controls the training speed
A small learning rate makes training slow
A large learning rate can make training unstable
Training a model requires a lot of data
Training a model requires a good computer
GPUs make training faster
The model learns patterns from the training data
The model makes predictions on new data
Python is the most popular language for machine learning
I use Python to build machine learning models
I use TensorFlow to build neural networks
I use Keras to build deep learning models
I use pandas to clean the data
I use numpy for numerical computing
Keras is a library for deep learning
TensorFlow is a framework for machine learning
Natural language processing helps computers understand text
Natural language processing is used in chatbots
Language models predict the next word
Language models learn from large amounts of text
A chatbot can answer questions from users
A recurrent neural network can process sequences
An LSTM can remember long term patterns
An LSTM is a type of recurrent neural network
Embedding layers convert words into vectors
Words with similar meanings have similar vectors
The tokenizer converts words into numbers
The tokenizer builds a vocabulary from the text
The softmax layer gives the probability of each word
The model predicts the word with the highest probability
Text generation uses a language model
Text generation predicts one word at a time
Computer vision helps computers understand images
Computer vision is used in self driving cars
Reinforcement learning learns from rewards
Supervised learning uses labeled data
Unsupervised learning finds patterns in unlabeled data
Classification predicts a category
Regression predicts a number
Feature engineering improves the model
Data engineers build pipelines to move data
Data pipelines clean and store the data
I am building a chatbot
I am building a language model
I am learning python programming
I am learning natural language processing
I want to learn natural language processing
I want to become a machine learning engineer
I want to become a data engineer
I want to build a chatbot
I want to build a language model
I love building projects
I love learning new things
I like solving problems
I like working with data
Practice makes a better engineer
Building projects is the best way to learn
Learning takes time and practice
Projects help you learn faster"""

data = data.strip() + "\n" + extra_data

In [91]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

In [92]:
tokenizer = Tokenizer()

In [93]:
tokenizer.fit_on_texts([data])

In [94]:
tokenizer.word_index

{'the': 1,
 'learning': 2,
 'i': 3,
 'a': 4,
 'model': 5,
 'data': 6,
 'is': 7,
 'to': 8,
 'machine': 9,
 'neural': 10,
 'deep': 11,
 'can': 12,
 'learn': 13,
 'training': 14,
 'want': 15,
 'language': 16,
 'networks': 17,
 'from': 18,
 'am': 19,
 'build': 20,
 'of': 21,
 'network': 22,
 'patterns': 23,
 'learns': 24,
 'predicts': 25,
 'word': 26,
 'models': 27,
 'use': 28,
 'love': 29,
 'artificial': 30,
 'intelligence': 31,
 'for': 32,
 'text': 33,
 'like': 34,
 'used': 35,
 'in': 36,
 'on': 37,
 'words': 38,
 'time': 39,
 'with': 40,
 'good': 41,
 'natural': 42,
 'processing': 43,
 'building': 44,
 'powerful': 45,
 'uses': 46,
 'are': 47,
 'problems': 48,
 'next': 49,
 'takes': 50,
 'more': 51,
 'layers': 52,
 'clean': 53,
 'new': 54,
 'helps': 55,
 'rate': 56,
 'makes': 57,
 'computer': 58,
 'python': 59,
 'chatbot': 60,
 'engineer': 61,
 'projects': 62,
 'interesting': 63,
 'useful': 64,
 'solve': 65,
 'many': 66,
 'studying': 67,
 'examples': 68,
 'improves': 69,
 'improve': 70,


In [95]:
input_sequences = []
for sentence in data.split('\n'):
  token_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(token_sentence)):
    input_sequences.append(token_sentence[:i+1])


In [96]:
input_sequences

[[3, 29],
 [3, 29, 9],
 [3, 29, 9, 2],
 [3, 29],
 [3, 29, 11],
 [3, 29, 11, 2],
 [3, 29],
 [3, 29, 30],
 [3, 29, 30, 31],
 [3, 34],
 [3, 34, 9],
 [3, 34, 9, 2],
 [3, 34],
 [3, 34, 11],
 [3, 34, 11, 2],
 [9, 2],
 [9, 2, 7],
 [9, 2, 7, 63],
 [9, 2],
 [9, 2, 7],
 [9, 2, 7, 45],
 [9, 2],
 [9, 2, 7],
 [9, 2, 7, 64],
 [11, 2],
 [11, 2, 7],
 [11, 2, 7, 45],
 [11, 2],
 [11, 2, 7],
 [11, 2, 7, 63],
 [11, 2],
 [11, 2, 46],
 [11, 2, 46, 10],
 [11, 2, 46, 10, 17],
 [30, 31],
 [30, 31, 7],
 [30, 31, 7, 105],
 [30, 31, 7, 105, 1],
 [30, 31, 7, 105, 1, 106],
 [30, 31],
 [30, 31, 7],
 [30, 31, 7, 107],
 [30, 31, 7, 107, 64],
 [10, 17],
 [10, 17, 47],
 [10, 17, 47, 45],
 [10, 17],
 [10, 17, 12],
 [10, 17, 12, 13],
 [10, 17, 12, 13, 23],
 [10, 17],
 [10, 17, 47],
 [10, 17, 47, 35],
 [10, 17, 47, 35, 36],
 [10, 17, 47, 35, 36, 11],
 [10, 17, 47, 35, 36, 11, 2],
 [11, 2],
 [11, 2, 12],
 [11, 2, 12, 65],
 [11, 2, 12, 65, 108],
 [11, 2, 12, 65, 108, 48],
 [9, 2],
 [9, 2, 12],
 [9, 2, 12, 65],
 [9, 2, 12, 65

In [97]:
max_len = max([len(i) for i in input_sequences])

In [98]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_input = pad_sequences(input_sequences, maxlen = max_len,padding = 'pre')

In [99]:
padded_input

array([[  0,   0,   0, ...,   0,   3,  29],
       [  0,   0,   0, ...,   3,  29,   9],
       [  0,   0,   0, ...,  29,   9,   2],
       ...,
       [  0,   0,   0, ...,  62, 212, 213],
       [  0,   0,   0, ..., 212, 213,  13],
       [  0,   0,   0, ..., 213,  13,  86]], dtype=int32)

In [100]:
X = padded_input[:,:-1]
print(X)

[[  0   0   0 ...   0   0   3]
 [  0   0   0 ...   0   3  29]
 [  0   0   0 ...   3  29   9]
 ...
 [  0   0   0 ...   0  62 212]
 [  0   0   0 ...  62 212 213]
 [  0   0   0 ... 212 213  13]]


In [101]:
X[0].shape

(8,)

In [102]:
y = padded_input[:,-1]

In [103]:
y

array([ 29,   9,   2,  29,  11,   2,  29,  30,  31,  34,   9,   2,  34,
        11,   2,   2,   7,  63,   2,   7,  45,   2,   7,  64,   2,   7,
        45,   2,   7,  63,   2,  46,  10,  17,  31,   7, 105,   1, 106,
        31,   7, 107,  64,  17,  47,  45,  17,  12,  13,  23,  17,  47,
        35,  36,  11,   2,   2,  12,  65, 108,  48,   2,  12,  65,  66,
        48,  19,   2,   9,   2,  19,   2,  11,   2,  19,  67,  30,  31,
        19,  67,  10,  17,   5,  24,  18,   6,   5,  25,   1,  49,  26,
         5,  12,  13,  23,   5,   7, 109,  37,   6,  10,  22,  24,  23,
        10,  22,  25,  38,   7, 110,  32,   9,   2,   7,  35,   8, 111,
         1,   5,   1,   5,  50,  39,   1,  10,  22,  50,  39,   5,  24,
        18,  68,   5,  69,  40,  51,   6,   6,  12,  70,   1,   5,   2,
        27,  13,  18,   6,   2,  27,  28,  10,  17,  17,  13,  18,  68,
        15,   8,  13,   9,   2,  15,   8,  13,  11,   2,  15,   8,  20,
         4,  10,  22,  15,   8,  20,   4, 112,   5,  15,   8,  7

In [104]:
len(tokenizer.word_index)

213

In [105]:
y.shape

(628,)

In [106]:
from tensorflow.keras.utils import to_categorical
y= to_categorical(y,num_classes = 214)

In [107]:
X.shape

(628, 8)

In [108]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [109]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense , LSTM,Input

In [110]:
# model = Sequential()

# model.add(Embedding(62,50,input_length = 6))
# model.add(LSTM(100))
# model.add(Dense(62,activation='softmax'))

# model.summary()
model = Sequential()

model.add(Input(shape=(8,)))
model.add(Embedding(214, 110))
model.add(LSTM(170))
model.add(Dense(214, activation='softmax'))

In [111]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [112]:
model.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_13 (Embedding)        │ (None, 8, 110)         │        23,540 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_12 (LSTM)                  │ (None, 170)            │       191,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 214)            │        36,594 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 251,214 (981.30 KB)

 Trainable params: 251,214 (981.30 KB)

 Non-trainable params: 0 (0.00 B)

In [113]:
model.fit(X,y,epochs=300)

Epoch 1/300
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.0446 - loss: 5.2644
Epoch 2/300
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0605 - loss: 4.7939
Epoch 3/300
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0637 - loss: 4.6664
Epoch 4/300
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0780 - loss: 4.6161
Epoch 5/300
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.0955 - loss: 4.5293
Epoch 6/300
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.1274 - loss: 4.3962
Epoch 7/300
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.1592 - loss: 4.2246
Epoch 8/300
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.1990 - loss: 4.0421
Epoch 9/300
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.2150 - loss: 3.8352
Epoch 10/300
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2532 - loss: 3.6291
Epoch 11/300
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.2818 - loss: 3.4012
Epoch 12/300
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

In [114]:
import numpy as np

In [115]:
import time
text = "I"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=8, padding='pre')
  # predict
  probs = model.predict(padded_token_text, verbose=0)[0]
  pos = np.random.choice(len(probs), p=probs / probs.sum())

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

I use
I use python
I use python to
I use python to build
I use python to build machine
I use python to build machine learning
I use python to build machine learning models
I use python to build machine learning models use
I use python to build machine learning models use problems
I use python to build machine learning models use problems data
